FROM python:3.9

WORKDIR /code

COPY requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir -r /code/requirements.txt

# Копируем все нужные папки и файлы
COPY main.py /code/main.py
COPY utils /code/utils
COPY weights /code/weights

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]